version: '2'

services:
  master:
    image: scalac/spark
    environment:
      - NODE_TYPE=master
      - SPARK_MASTER_IP=${SPARK_MASTER_IP}
      - "constraint:spark.role==master"
    hostname: spark-master
    container_name: spark-master
    expose:
      - 6066
      - 7077
      - 8080
      - 18080
    ports:
      - "6066:6066"
      - "7077:7077"
      - "8080:8080"
      - "18080:18080"
    network_mode: host
    restart: unless-stopped

  worker:
    image: scalac/spark
    environment:
      - NODE_TYPE=slave
      - SPARK_NETWORK_NIC=${SPARK_NETWORK_NIC}
      - SPARK_MASTER_IP=${SPARK_MASTER_IP}
      - "affinity:container!=spark_worker*"
      - "constraint:spark.role==worker"
    expose:
      - 4040
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 8081
      - 18080
    ports:
      - "4040:4040"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
      - "7006:7006"
      - "8081:8081"
      - "18080:18080"
    network_mode: host
    restart: unless-stopped
